---
title: "Regression Project"
author: "Adrien Toulouse & Paul-Antoine Girard"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Avant preprocessing

```{r}
library(dplyr)
library(car)
```


```{r}
trainPP <- read.csv(file = 'train_preprocessed.csv')
```

```{r}
str(trainPP)
```

```{r}
trainPP$LogSalePrice <- log(trainPP$SalePrice)
trainPP <- select(trainPP, -c("SalePrice"))
plot(density(trainPP$LogSalePrice))
```


```{r}
price_lm = lm(LogSalePrice ~ ., data = trainPP)
summary(price_lm)
```

```{r}
select.variables.both = step(price_lm,scope= ~1,direction="both",trace=FALSE)
summary(select.variables.both)
```


```{r}
select.variables.backward = step(price_lm,scope= ~1,direction="backward",trace=FALSE) 
summary(select.variables.backward)
```

```{r}
extractAIC(select.variables.backward)
extractAIC(select.variables.both)
```

```{r}
par(mfrow=c(2,2)) 
plot(select.variables.both)
```

```{r}
acf(residuals(select.variables.both))
```

```{r}
influenceIndexPlot(select.variables.both)
```

```{r}
price_lm_2 = lm(LogSalePrice ~ YearBuilt + MSZoning, data = trainPP)
summary(price_lm_2)
```


